Avatar component
Developer-DAO/web3-ui pull request #157
Opened 2021-12-24 18:03 UTC by Dhaiwat10

Originally #110
Closes #66

## Description

> Add a brief description
Created a component for ENS avatars using @react/davatar library.

## 📝 Additional Information

Component takes in an address and displays ENS avatar if applicable. If not, displays a jazzicon. Size is customizable but default value is 50px.

<img width="1083" alt="Screen Shot 2021-12-13 at 9 16 02 AM" src="https://user-images.githubusercontent.com/54959624/145857934-517238b9-070c-468d-9835-1eefa7225a74.png">

2021-12-27 01:48 UTC, etr2460 approved these changes
a few comments, nothing blocking, but would be nice to have

2021-12-27 01:48 UTC, etr2460 commented on packages/components/src/components/Avatar/Avatar.stories.tsx
> +);
can we add a story for when the address doesn't have an avatar?

2021-12-27 01:48 UTC, etr2460 commented on packages/components/src/components/Avatar/Avatar.tsx
> +  size?: number;
should we try to use Chakra-UI sizes here? so that this accepts `xs`, `sm`, etc. too?

2021-12-29 07:13 UTC, with-heart commented
I think we should consider naming this something other than `Avatar`. Since we're based on Chakra which already exports an `Avatar` component, we're setting our users up for a potentially confusing situation. I'd suggest `EnsAvatar` since it's a specific type of avatar.

2021-12-29 07:19 UTC, with-heart requested changes
After looking at the source, I'd suggest that we close this. If all we're doing with the component is re-exporting another library's component (and making it less flexible in the process, since we reduce the props down to `size` and `avatar` only), I think we should recommend that users check out the other lib rather than including it directly in our lib.

If we built something on top of that library unique to `web3-ui`, it'd make a lot more sense to include that here.

2021-12-29 09:50 UTC, Dhaiwat10 commented
@with-heart that definitely sounds sensible and something I can agree with. What are your thoughts on this? @jwarshack @etr2460

2021-12-30 21:24 UTC, jwarshack commented
@Dhaiwat10 @etr2460 Agree with @with-heart. The only benefit would be convenience but probably not worth the tradeoff of less flexibility.

2021-12-31 11:59 UTC, Dhaiwat10 commented
@jwarshack Let's close this then! Sorry that your PR is going down the drain. We def need to learn from this and make sure we think things over before working on something. Thanks Jake ❤️

2021-12-31 11:59 UTC, closed without merging

2021-12-31 11:59 UTC, Dhaiwat10 commented
@allcontributors please add @jwarshack for code